const roles = {
  saloon: {
    name: "Салон",
    permissionCreateSaloon: false,
    permissionCreateModerator: false,
    permissionCreateService: true,
    permissionCreateServiceInstance: false,
    permissionRemoveClient: false,
    permissionRemoveMaster: false,
    permissionRemoveSaloon: false,
    permissionRemoveModerator: false,
    permissionRemoveService: true,
    permissionRemoveServiceInstance: false,
    permissionEditClient: false,
    permissionEditMaster: false,
    permissionEditSaloon: false,
    permissionEditModerator: false,
    permissionEditService: true,
    permissionEditServiceInstance: false,
  },
  master: {
    name: "Мастер",
    permissionCreateSaloon: false,
    permissionCreateModerator: false,
    permissionCreateService: false,
    permissionCreateServiceInstance: true,
    permissionRemoveClient: false,
    permissionRemoveMaster: false,
    permissionRemoveSaloon: false,
    permissionRemoveModerator: false,
    permissionRemoveService: false,
    permissionRemoveServiceInstance: true,
    permissionEditClient: false,
    permissionEditMaster: false,
    permissionEditSaloon: false,
    permissionEditModerator: false,
    permissionEditService: false,
    permissionEditServiceInstance: true,
  },
  client: {
    name: "Клиент",
    permissionCreateSaloon: false,
    permissionCreateModerator: false,
    permissionCreateService: false,
    permissionCreateServiceInstance: true,
    permissionRemoveClient: false,
    permissionRemoveMaster: false,
    permissionRemoveSaloon: false,
    permissionRemoveModerator: false,
    permissionRemoveService: false,
    permissionRemoveServiceInstance: true,
    permissionEditClient: false,
    permissionEditMaster: false,
    permissionEditSaloon: false,
    permissionEditModerator: false,
    permissionEditService: false,
    permissionEditServiceInstance: false,
  },
  moderator: {
    name: "Модератор",
    permissionCreateSaloon: true,
    permissionCreateModerator: false,
    permissionCreateService: false,
    permissionCreateServiceInstance: false,
    permissionRemoveClient: true,
    permissionRemoveMaster: true,
    permissionRemoveSaloon: true,
    permissionRemoveModerator: false,
    permissionRemoveService: true,
    permissionRemoveServiceInstance: true,
    permissionEditClient: true,
    permissionEditMaster: true,
    permissionEditSaloon: true,
    permissionEditModerator: false,
    permissionEditService: true,
    permissionEditServiceInstance: true,
  },
  administrator: {
    name: "Администратор",
    permissionCreateSaloon: true,
    permissionCreateModerator: true,
    permissionCreateService: true,
    permissionCreateServiceInstance: true,
    permissionRemoveClient: true,
    permissionRemoveMaster: true,
    permissionRemoveSaloon: true,
    permissionRemoveModerator: true,
    permissionRemoveService: true,
    permissionRemoveServiceInstance: true,
    permissionEditClient: true,
    permissionEditMaster: true,
    permissionEditSaloon: true,
    permissionEditModerator: true,
    permissionEditService: true,
    permissionEditServiceInstance: true,
  },
};

module.exports = {
  roles,
};
